print('THE AWESOME CALCULATOR')
print ("type your numbers below an the calculator will do the rest")
q=(int(float(input('type your first number here: '))))
w=(int(float(input('type your second number her: '))))
print('                                          ')
print('the Addition of your numbers are=',q+w,)
print('                                          ')
print('the subtraction of your numbers are=',q-w)
print('                                          ')
print('the multiplication of your numbers are=',q*w)
print('                                           ')
print('the division of you numbers are=',q/w)
